apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: stocks
  labels:
    app: postgres
spec:
  replicas:  1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      annotations:
        metrics.dynatrace.com/path: /stats/prometheus
        metrics.dynatrace.com/port: "15020"
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/secure: "false"
      namespace: stocks
      labels:
        app: postgres
        app.kubernetes.io/version: 1.6.0
        app.kubernetes.io/part-of: Stocks
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: stocks-secret
                  key: DT_PG_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stocks-secret
                  key: DT_PG_PASS
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: stocks-configmap
                  key: DB_NAME
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: stocks
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
